services:
  db:
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432